/* THIS FILE HAS ALL THE RESPONSES TO BE RETURNED FROM CONTROLLERS */

module.exports = {
  LOGIN_SUCCESS: "Logged in",
  USER_ALREADY_EXISTS: "Username or email already taken",
  USER_NOT_FOUND: "User not found",
  USERS_NOT_FOUND: "Users not found",
  FAQ_NOT_FOUND: "FAQ not found",
  SESSION_NOT_FOUND: "User session does not exist",
  LOG_OUT: "Logged out",
  FILE_INVALID: "Please provide a valid file!",
  NOT_FOUND: "Not found",
  CREATE_MATCH_ERROR: "Could not create match!",
  JOINED_MATCH: "Match joined successfully!",
  PAYLOAD_INVALID: "Please provide valid payload!",
  RESULT_EXISTS: "Match already settled!",
  ALREADY_SUBMITTED: "You already submitted result",
  MATCH_NOT_FOUND: "Match doesn't exist",
  AlREADY_JOINED: "Already joined match",
  GAMES_NOT_FOUND: "Games not found",
  USER_REGISTRATION_FAILURE: "Could not create user",
  MISSING_PARAMETERS: "Missing parameters in the request body",
  FAILURE: "Something went wrong",
  INVALID_COOKIE: "Invalid or corrupt cookie provided",
  INVALID_CREDENTIALS: "Username or password is incorrect",
  INVALID_PASSWORD: "Incorrect password provided",
  INVALID_USERNAME: "Username is incorrect",
  UNAUTHORIZED: "Not authorized for access",
  INCORRECT_PASSWORD: "Incorrect password was provided",
  UNIQUE_USERNAME_EMAIL: "Username and email must be unique.",
  TOKEN_NOT_FOUND: "Token not found",
  NOT_A_MEMBER: "You are not a member of this chat",
  GAME_NOT_FOUND: "This game does not exist",
  NOT_FREE_TO_PLAY: "This game is not free to play",
  INVALID_TOKEN: "Token is invalid",
  GAME_PROFILE_NOT_FOUND: "Game profile not found",
  SITE_LOGO_NOT_REMOVED: "Could not remove site logo",
  NOT_REMOVED: "Could not remove",
  GAME_NOT_ARCHIVED: "Could not archive game",
  NOT_UPDATED: "Could not update",
  NOT_UPLOADED: "Failed to upload",
  GAME_PROFILE_NOT_CREATED: "Could not create game profile",
  CHAT_NOT_FOUND: "Chat room does not exist",
  MEMBERS_NOT_FOUND: "No chat members found",
  MESSAGE_NOT_POSTED: "Could not post message",
  MATCH_NOT_JOINED: "Could not join match",
  NOT_ENOUGH_PLAYERS: "Not enough players in match",
  NOT_ENROLLED: "You are not enrolled in this match",
  NOT_SUBMITTED: "Result not submitted",
  SESSION_NOT_REMOVED: "Error removing user session",
  REFRESH_TOKEN_NOT_UPDATED: "Could not update refresh token",
  CONFIGS_NOT_FOUND: "Game configs not found",
  NO_RESULT: "No results found",
  MATCHES_NOT_FOUND: "No matches found",
  EMAIL_NOT_VERIFIED: "Could not verify email",
  EMAIL_VERIFICATION_NOT_GENERATED: "Could not generate email verification",
  SESSION_NOT_CREATED: "Could not create user session",
  ALREADY_LOGGED_OUT: "You already logged out",
  CHAT_NOT_CREATED: "Could not create match chat",
  TIMEZONE_UPDATED: "Time Zone Update Sucessfully",
  NOT_TIMEZONE_UPDATED: "Timezone Not Update, Try again",
  IN_ANOTHER_MATCH: "You are already in another match",
  MATCH_START_REQUEST_FAILED: "Could not send start request",
  MATCH_IN_PROGRESS: "Match already in progress",
  MATCH_NOT_FOUND: "Match not found",
  NOT_GAME_UPDATED: "Game is Not Update, Try again",
  NOT_TITLE_UPDATED: "Title Can Not Be Empty, Try again",
  NOT_BANNER_UPDATED: "Banner is Not Update, Try again",
  VERIFY_EMAIL: "Please verify your email before continuing",
  NOT_CREATED_PLATFORM: "Platform Is Not Created",
  NOT_BEST_OF_EMPTY: "Best of can not be empty",
  NOT_LEVEL_EMPTY: "Level of can not be empty",
  INACTIVE_USER: "User is inactive please contact the admin",
  SHOPS_NOT_FOUND: "Shops not found",
  SHOP_CREATE_ERROR: "Error in creating shop!",
  SHOP_CREATED: "Shop created Successfully!",
  SHOP_UPDATED: "Shop updated Successfully!",
  SUCCESS: "success",
  NOT_ENOUGH_CREDITS: "You don't have enough credits",
  WINNER_NOT_SET: "Could not set match winner",
  GAME_ARCHIVE_ERROR: "This game still has matches in progress, Can not archive!",
  GAME_ARCHIVE_ALL_MATCHES_COMPLETED: "This game matches are all completed.",
  GAME_ARCHIVE_DOESNT_HAVE_ANY_MATCH: "This game doesn't have any match",
  RESEND_VERIFICATION_ERROR: "Could not send resent link, Something went wrong!",
  RESEND_VERIFICATION_LIMIT_ERROR:
    "Could not send resent link, Limit exceeded!. Try again after 24 hours.",
  DISPUTE_NOT_RESOLVED: "Could not resolve dispute",
  TICKET_NOT_FOUND: "Ticket not found",
  DISPUTE_ROOM_NOT_FOUND: "Dispute room not found",
  VERIFY_EMAIL: "Kindly verify your email before continuing",
};
