const { DataTypes } = require("sequelize");
const sequelize = require("../config/db.config");

const Notifier = sequelize.define(
  "notifiers",
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      allowNull: false,
      primaryKey: true,
    },
    notificationDetailId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    notifierId: {
      type: DataTypes.INTEGER,
    },
    autoGenerated: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },
  },
  { underscored: true }
);

module.exports = Notifier;
